title: "構造と盲点"
summary: "構造工学の天才・海野啓介が、独自開発した「リモート捜査スティック」を使って密室殺人事件を解決していく理系ミステリー小説。引きこもりの海野は現場に行かず、助手の九条紗英が送る3Dデータと構造解析だけで真相を暴く。"
topics: ["小説", "ミステリー", "理系ミステリー", "構造工学", "安楽椅子探偵", "科学推理", "3Dスキャン", "密室トリック"]
published: true
price: 0
chapters:
  - "01"