title: "戦国砲術師　～高専生のポケコンが変えた歴史～"
summary: "現代の高専生がポケコンPC-G850VSとともに戦国時代にタイムスリップ。数学と物理の知識を活かして砲術を革新し、歴史を変える物語。エネループ電池の残量とともに描かれる、科学技術による戦国絵巻。"
topics: ["小説", "歴史", "科学技術", "戦国時代", "タイムスリップ", "数学", "物理", "砲術"]
published: true
price: 0
chapters:
  - "prologue"
  - "shrine-encounter"
  - "slide-rule-creation"
  - "first-artillery-test"
  - "lord-recruitment"
  - "artillery-corps-formation"
  - "first-battle"
  - "innovation-spread"
  - "setback-and-recovery"
  - "strategic-revolution"
  - "new-era"