title: "戦国砲術師"
summary: "現代の理系大学生が戦国時代にタイムスリップし、数学と物理学の知識を活かして砲術の革新を起こす物語"
topics: ["小説", "戦国時代", "転生", "歴史", "ファンタジー"]
published: false
price: 0
chapters:
  - episode_00_prologue
  - episode_01_shrine_encounter
  - episode_02_slide_rule_creation
  - episode_03_first_artillery_test
  - episode_04_lord_recruitment
  - episode_05_artillery_corps_formation
  - episode_06_first_battle
  - episode_07_innovation_spread
  - episode_08_setback_and_recovery
  - episode_09_strategic_revolution
  - episode_10_new_era