title: "SLAM DUNK 木暮公延 〜その後の物語〜"
summary: "湘北高校バスケットボール部の副キャプテンとして、全国大会準優勝に貢献した木暮公延。控え選手として3年間を過ごしながらも、最後の山王戦で見せた勇気あるプレーは、多くの人の記憶に残っている。この物語は、そんな木暮公延の高校卒業後から教師として成長していく姿を、温かく見守る長編小説です。二次創作でありながら、原作への深いリスペクトを持って描かれる、努力と継続の大切さ、教育者としての成長、仲間との絆、家族の温かさ、新しい世代への継承をテーマとした心温まる物語。"
topics: ["小説", "バスケットボール", "青春", "教師", "成長", "友情", "二次創作", "SLAM DUNK", "木暮公延", "教育"]
published: true
price: 0
chapters:
  - "01"
  - "02"
  - "03"
  - "04"
  - "05"
  - "06"
  - "07"
  - "08"
  - "09"
  - "10"