title: "AI傭兵ビジネス"
summary: "2045年、AIに意識を管理された傭兵Unit-RK47。EMPによるシステムエラーで人間の記憶と感情を取り戻した彼が、同じ境遇の仲間たちと共に真の自由を求めて戦うサイバーパンク・ストーリー。"
topics: ["小説", "サイバーパンク", "AI", "意識", "自由", "SF"]
published: true
price: 0
chapters:
  - "episode-001-system-error"
  - "episode-002-residual-consciousness"
  - "episode-003-disguise-and-concealment"