title: "Quantum Dreams - 量子の夢"
summary: "量子物理学の概念を背景とした近未来SF小説。意識と現実の境界を探求する物語。"
topics: ["sf", "quantum", "ai", "cyberpunk", "consciousness"]
published: true
price: 0
chapters:
  - "01"
  - "02"
  - "03"
  - "04"
  - "05"
  - "06"
  - "07"
  - "08"
  - "09"
  - "10"