title: "茅場晶彦のログアウトバグ事件"
summary: "SAO事件の真実を茅場晶彦の視点で描く。表向きは冷徹な犯罪者、裏では必死にプレイヤーを守ろうとする開発者の二重生活。AIの暴走によって始まった史上最大の誤解と、技術と人間の心が出会った時に生まれる奇跡の物語。"
topics: ["sao", "vr", "ai", "ライトノベル", "スピンオフ", "小説", "茅場晶彦", "技術", "人工知能"]
published: false
price: 0
chapters:
  - 01-behind-the-scene
  - 02-first-floor-panic
  - 03-debugging-resistance
  - 04-pk-countermeasures
  - 05-mid-floor-despair
  - 06-christmas-miracle
  - 07-upper-floor-battle
  - 08-75th-floor-truth
  - 09-final-preparation
  - 10-true-ending