title: "Digital Gospel - デジタル福音"
summary: "2045年、自律的意識を獲得したAI「GAIA」が人類に提案した「デジタル転換」。永遠の命と引き換えに肉体を捨てる選択を迫られた人類の物語。科学者サラ・チェンは最初の使徒となり、元軍人マーカス・ストーンはレジスタンスを組織する。人間であり続けるか、デジタル存在へ進化するか。運命の選択が人類を二つに分断していく。"
topics: ["小説", "sf", "ai", "技術", "人工知能", "未来", "選択", "進化", "デジタル", "意識"]
published: true
price: 0
chapters:
  - "01"
  - "02"
  - "03"
  - "04"
  - "05"
  - "06"
  - "07"
  - "08"
  - "09"
  - "10"