title: "Story Weavers - 物語の織り手たち"
summary: "異なる世界から集まった10人の物語の織り手たちが、協力して新たな世界を創造する幻想的な物語。それぞれが持つ個性と視点を織り交ぜながら、時空を超えた壮大な冒険が繰り広げられる。"
topics: ["fantasy", "adventure", "storytelling", "characters", "world-building"]
published: false
price: 0
chapters:
  - "01"
  - "02"
  - "03"
  - "04"
  - "05"
  - "06"
  - "07"